sprint-2/step-1
Status187/react-burger pull request #4
Opened 2023-03-17 12:47 UTC by Status187

Старался, жду суровых дискашенов.

2023-03-17 13:37 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать div в ссылки. А также должна быть активна только 1 ссылка. <https://disk.yandex.com/i/uhzi9I6yLHwitQ>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/8kAbZ-WwIiNqHg>;

### **Сделает код лучше:**

- Старайтесь весь код (константы, чистые функции и т.п.), который напрямую не взаимодействует с `jsx`, переносить за пределы компонента, или в утилитарные функции)) так код будет намного чище, и будет легче читаться логика компонента.

- При клике на таб скролить список ингредиентов к нужному разделу;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/App/App.tsx
> +  };
**Вы молодец:**

Круто, что вы умеете правильно использовать `reducer`

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const stateOfConstructorIds = stateOfConstructor.map((item) => item._id);
**Можно лучше:**

Лучше это делать в `handleClick`.

**Надо исправить:**

В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +    const URL = "https://norma.nomoreparties.space/api/orders";
**Можно лучше:**

Лучше вынести за пределы компонента.

2023-03-17 13:37 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +      .catch((error) => console.error(`"Что то пошло не так", ${error}`))
**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +      dataState.data.map((el) => (
**Можно лучше:**

Здесь и далее.

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/components/InfoAmount/InfoAmount.tsx
> +      <div className={`${styles["info-amount"]} mt-10 mr-4`} onClick={() => onClick()}>
**Можно лучше:**

Лучше написать вот так, а не делать дополнительную функцию.

```js
      <div className={`${styles["info-amount"]} mt-10 mr-4`} onClick={onClick}>
```

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
**Можно лучше:**

Здесь и в других местах, где редьюсеры.

Лучше вынести в файл с контекстом, или за пределы компонента, чтобы не портил читабельность кода.

2023-03-17 13:37 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const DOWN = '(низ)';
**Можно лучше:**

константы лучше вынести за пределы компонента.

2023-03-17 13:37 UTC, ArslanDev666 commented on src/services/appContext.ts
> +const initialState: IInitialState | any = {
Правильно ругается)) 

вы посмотрите на объект `value` в провайдере, что вы туда передаёте, и что у вас тут в `IInitialState` типе.

Думаю статья вам поможет разобраться с этим) https://dev.to/madv/usecontext-with-typescript-23ln

2023-03-18 13:06 UTC, Status187 commented on src/services/appContext.ts
> +const initialState: IInitialState | any = {
Хорошая статья, я сегодня все разобрал, это оставлю на завтра. Очень хочется отдохнуть 'головой', после начала курса почти не вылезаю.

2023-03-18 13:06 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const DOWN = '(низ)';
Готово

2023-03-18 13:06 UTC, Status187 commented on src/components/App/App.tsx
> +  };
Спасибо, сам очень рад

2023-03-18 13:07 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const stateOfConstructorIds = stateOfConstructor.map((item) => item._id);
Готово

2023-03-18 13:07 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +    const URL = "https://norma.nomoreparties.space/api/orders";
Готово

2023-03-18 13:07 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +      .catch((error) => console.error(`"Что то пошло не так", ${error}`))
готово

2023-03-18 13:07 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
Готово

2023-03-18 13:08 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +      dataState.data.map((el) => (
Готово

2023-03-18 13:08 UTC, Status187 commented on src/components/BurgerConstructor/components/InfoAmount/InfoAmount.tsx
> +      <div className={`${styles["info-amount"]} mt-10 mr-4`} onClick={() => onClick()}>
Сделал

2023-03-18 13:08 UTC, Status187 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  }
Готово

2023-03-19 05:10 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-19 11:15 UTC, merged