sprint-3/step-1
Status187/react-burger pull request #6
Opened 2023-05-10 11:07 UTC by Status187

Прошу помочь, столько всего нужно сделать, запутался совсем. Дайте, пожалуйста, какие нибудь подсказки, идет с трудом.

2023-05-10 12:19 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с куками
- После регистрации происходит автоматическая авторизация
- Хорошая работа с хранилищем юзера

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный юзер не должен иметь возможность сделать заказ
- После авторизации невозможно попасть на страницу профиля
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.
- При перезагрузке страницы - слетает авторизация, хотя в куках есть токены. 
- В инпут для кода восстановления на странице `reset-password` невозможно ничего ввести. Когда поправите этот момент проверьте, что восстановление пароля работает и в запросе уходит именно веденный токен. 
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент 
-```
{path="/"}:
setCookie('name', value, { path: '/' }).

```
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.
- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Роуты `/profile` и все вложенные в `/profile` маршруты должны быть доступны только авторизованным пользователям, т. е. защищены HOC-компонентом `ProtectedRoute`- его необходимо создать.

**Если у вас что-то не получается - вы всегда можете обратиться к своему наставнику за помощью.**

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-10 12:19 UTC, andryxxa93 commented on src/components/App/App.tsx
> +            <Route path="/login" element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-10 12:19 UTC, andryxxa93 commented on src/pages/Register/Register.tsx
> +  const onChange = (e: { target: { value: React.SetStateAction<string>; }; }) => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-05-10 12:19 UTC, andryxxa93 commented on src/pages/Register/Register.tsx
> +      { user ? <Navigate to={ location.state?.from || '/' } /> :
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-05-11 06:29 UTC, Status187 commented on src/components/App/App.tsx
> +            <Route path="/login" element={<LoginPage />} />
Да, переписал.

2023-05-11 06:34 UTC, Status187 commented on src/pages/Register/Register.tsx
> +  const onChange = (e: { target: { value: React.SetStateAction<string>; }; }) => {
Добавил хук.

2023-05-16 08:35 UTC, andryxxa93 commented
Супер, вы отлично поработали, осталось два небольших замечания и работа будет принята!
**Необходимо исправить**
- Если авторизоваться и обновить страницу, то на странице профиля в инпутах не отображаются данные юзера
- Изменение данных юзера вызывает сразу два запроса. Первый - просто get запрос данных юзера, второй - запрос на изменение данных. Должен быть только один запрос `patch`

2023-05-16 15:23 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-22 11:05 UTC, merged